name: analytics
description: Analytics module for Tic-Tac-Toe app
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.10.7
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  firebase_analytics: ^12.1.1
  flutter_riverpod: ^3.2.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
