name: tic_tac_toe_workspace
publish_to: 'none'

environment:
  sdk: ^3.10.7
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analytics: any
  logs: any
  core: any
  game: any
  login: any

workspace:
  - apps/tic_tac_toe
  - packages/analytics
  - packages/core
  - packages/game
  - packages/login
  - packages/logs

dev_dependencies:
  flutter_lints: ^6.0.0
  melos: ^7.4.0

melos:
  scripts:
    analyze:
      run: melos exec -- flutter analyze
      description: Run flutter analyze in all packages
    test:
      run: melos exec -- flutter test
      description: Run flutter test in all packages
    clean:
      run: melos exec -- flutter clean
      description: Clean all packages
    gen-l10n:
      run: melos exec -- flutter gen-l10n
      description: Generate traduction in all packages
