name: game
description: Game module for Tic-Tac-Toe app
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.10.7
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.0
  equatable: ^2.0.8
  go_router: ^17.0.1
  intl: any
  core: any
  analytics: any
  logs: any
  login: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: any

flutter:
  generate: true
  assets:
    - assets/
