name: login
description: Login module for Tic-Tac-Toe app
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.10.7
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.7
  flutter_riverpod: ^3.2.0
  go_router: ^17.0.1
  shared_preferences: ^2.5.4
  intl: any
  core: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: any

flutter:
  generate: true
  assets:
    - assets/
