name: login
description: Login module for Tic-Tac-Toe app
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.10.7
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_riverpod: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: any
